### ISSUE TITLE
Lower triangular phylip input

### ISSUE THREAD

**Issue by ptlcc** [somme89/rapidNJ#1]
Would it be possible to include input as a lower triangular phylip matrix.

**Comment by somme89** [comment]
Hi,
It is definitely possible to provide this input option. I don't have time to work on this project right now but I'll keep it in mind for future updates. You could write a simple script that expanded a lower triangular matrix to a full phylip formatted distance matrix.

**Comment by ptlcc** [comment]
Then I will just go with Clearcut or other options. As this limitation will make it substantially slower, use excessive memory and quadruple the disk access required just to load the matrix, compared to other options.
