### ISSUE TITLE
compile rapidNJ for macOS M1?

### ISSUE THREAD

**Issue by chlangley** [somme89/rapidNJ#3]
I was hoping to run rapidNJ on my macOS M1 MBP.  

Any chance someone can update the Makefile of the macOS M1?

Thanks in advance.
Cheers,
Chuck

**Comment by somme89** [comment]
Hi Chuck,

I don't have access to an M1 CPU so right now there's no plans to support
this type of processor. Perhaps run it in a VM?

Best,
Martin

**Comment by chlangley** [comment]
Thanks for the info.  Totally understandable.  Just thought I would check.  It work well on my server. So no great loss.

Thank of the good tool.

Cheers,
Chuck
