### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by sassy-crick** [somme89/rapidNJ#4]
Dear maintainers,

I need to install the code as part of a larger installation I am doing. We are using [EasyBuild](https://easybuild.io/) on our cluster and, apart from that, it would be good to have a proper release, tag or otherwise, so the installation is more reproducible. 

Would it be possible to do that?

Kind regards

**Comment by somme89** [comment]
Hi,

I created a release which you can use. This code is in maintenance mode so I don't expect to create new releases any time soon.
