### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by sassy-crick** [somme89/rapidNJ#5]
Dear Madam, dear Sir,

first: thanks for dealing with issue #4 that quickly. Much appreciated. One minor tip: it is better to have the file name of the release as something like `v.2.3.3` rather than `latest`.

That aside, there seem to be some files missing. 
If I am replacing `-msse2` with the more general `-march=native` I get:
```
src/distanceCalculation/KimuraDistance.cpp:10:10: fatal error: bitDistanceProteinPopCnt.hpp: No such file or directory
   10 | #include "bitDistanceProteinPopCnt.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:52: obj/distanceCalculation/KimuraDistance.o] Error 1
```
Looking into `src/distanceCalculation/KimuraDistance.cpp` at line 10 it reads:
```
#ifdef __SSE4_2__
#include "bitDistanceProteinPopCnt.hpp"
#include "bitDistanceGapPopCnt.hpp"
#endif
```
Both files are not in the tarball. I was hunting around for them at various other GitHub pages but could not find them. 
That raises two questions for me:
- can one only use `-msse2` 
- is there a particular reason why these files are missing?

I am installing the software on our HPC cluster and thus it would be good to have a highly optimized package if that makes sense, rather than a generic build.

Thanks again for your prompt help, much appreciated!

**Comment by somme89** [comment]
Hi,

At the time this program was written, SSE4.2 was the lastest SIMD instruction set and some experiments were made using these new instructions. I guess I never cleaned up the code so if you enable SSE4.2 it tries to include files that no longer exists. My guess is that -march=native will enable __SSE4.2__ . The code was hand-optimized for SSE2 so enabling newer SIMD instructions probably won't increase performance.

I've made a commit where the offending includes are removed. Perhaps that enough to get it working using -march=native.

**Comment by sassy-crick** [comment]
Thanks for the quick response, much appreciated. These are the background informations I don't have, obviously. 

In that case I will simply stick to the optimisation which are in the `Makefile`. It is just confusing that the two files are not around any more. 
I will refer to this issue when I am oping the PR for that software with EasyBuild, so others know why it has been done in that specific way.
