### ISSUE TITLE
Sequence length error on uniform length sequence file

### ISSUE THREAD

**Issue by ryandkuster** [somme89/rapidNJ#6]
While producing trees for many files, I encountered the following error using version 2.3.3:
```
ERROR: Sequence 11 has length 9535 while the preceding sequences in the alignment which have length 6813
```

Usage:
```
rapidnj test.fasta --input-format fa --bootstrap 1000 --alignment-type d > test.tree
```

After inspecting the [file](https://github.com/somme89/rapidNJ/files/13366490/test.fasta.gz), all sequences are 6813 in length. If I reorder sequence 11 to the beginning of the file, the error still states sequence 11 is length 9535. If I change the name of a sequence _header_ by a single character, the command works just fine.

Thanks!

**Comment by somme89** [comment]
Hi Ryan,

Seems like a problem with the sequence parser. Give me some time to investigate and I'll push a fix for the problem.

**Comment by somme89** [comment]
I've pushed a fix for the problem.
